services:
  - type: web
    name: medium-scraper
    env: node
    plan: free
    buildCommand: ./install-chrome.sh && npm install
    startCommand: node app.js
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'true'
